// BROWLETTO MENU DATA
// ⚠️ IMPORTANT: This was transcribed from photos of your physical menu.
// Please scan through and correct any price/name mistakes before going live.
// Structure: each category has a name, an icon (emoji, swap anytime), and items[{name, price}]

const MENU = [
  {
    category: "Nutella Supremacy",
    icon: "🍫",
    items: [
      { name: "Plain Nutella", price: 130 },
      { name: "Nutella Brownie", price: 150 },
      { name: "Nutella Oreo", price: 150 },
      { name: "Nutella Kitkat", price: 150 },
      { name: "Nutella Hazelnut", price: 160 },
      { name: "Nutella Oreo Brownie", price: 160 },
      { name: "Nutella Oreo Kitkat", price: 160 },
      { name: "Nutella Nutties", price: 160 },
      { name: "Nutella Almonds", price: 170 },
      { name: "Nutella Nutties Rocher", price: 190 },
    ],
  },
  {
    category: "Crazy Thick Shakes",
    icon: "🥤",
    items: [
      { name: "Plain Vanilla", price: 70 },
      { name: "Plain Rose", price: 70 },
      { name: "Choco Chocochips", price: 90 },
      { name: "Belgium Chocochips", price: 90 },
      { name: "Munch", price: 90 },
      { name: "Rose Gulkand", price: 90 },
      { name: "Gems Of Gems", price: 100 },
      { name: "Paan Masti", price: 100 },
      { name: "Butterscotch", price: 110 },
      { name: "Oreo", price: 120 },
      { name: "Kitkat Crunch", price: 120 },
      { name: "Swiss Chocolate", price: 130 },
      { name: "Red Velvet", price: 130 },
    ],
  },
  {
    category: "Brownie Beasts (Thick Shakes)",
    icon: "🍪",
    items: [
      { name: "Brownie Loaded", price: 120 },
      { name: "Micha Brownie", price: 130 },
      { name: "Brownie Rocks", price: 140 },
      { name: "Brownie Crunch", price: 150 },
      { name: "Brownie Kitkat", price: 150 },
      { name: "Brownie Swiss", price: 150 },
      { name: "Brownie Nutties", price: 150 },
      { name: "Hazelnut Brownie", price: 150 },
      { name: "International Brownie", price: 150 },
      { name: "Brownie Oreo Kitkat", price: 160 },
      { name: "Brownie Nutella Kitkat", price: 170 },
      { name: "Brownie Nutties Rocher", price: 170 },
    ],
  },
  {
    category: "Fruit Burst",
    icon: "🍓",
    items: [
      { name: "Strawberry", price: 80 },
      { name: "Mango", price: 90 },
      { name: "Pineapple", price: 100 },
      { name: "Litchi", price: 120 },
      { name: "Sitafal", price: 130 },
      { name: "Chikoo", price: 130 },
      { name: "Blueberry", price: 130 },
      { name: "Strawberry Delight", price: 140 },
      { name: "Mango Alphonso", price: 150 },
      { name: "Mango Malai", price: 170 },
    ],
  },
  {
    category: "Cadbury Shakes",
    icon: "🍫",
    items: [
      { name: "Silky Affair", price: 120 },
      { name: "Cadbury Crackle", price: 130 },
      { name: "Roasted Almond Chocolate", price: 150 },
      { name: "Cadbury Fruit And Nuts", price: 150 },
      { name: "Hazelnut Silk", price: 170 },
    ],
  },
  {
    category: "Browletto Special (OG Thiccs)",
    icon: "⭐",
    items: [
      { name: "Caramel", price: 140 },
      { name: "Chocolava", price: 140 },
      { name: "Chocobar", price: 150 },
      { name: "Crunchy Crispello", price: 150 },
      { name: "Tiramisu", price: 150 },
      { name: "Motichoor", price: 150 },
      { name: "Nutella Biscoff", price: 160 },
      { name: "Coconut Biscoff", price: 170 },
      { name: "Mango Biscoff", price: 190 },
    ],
  },
  {
    category: "Biscoff",
    icon: "🍯",
    items: [{ name: "Lotus Biscoff", price: 170 }],
  },
  {
    category: "Dry Fruits",
    icon: "🌰",
    items: [
      { name: "Kesar Badam / Pista", price: 100 },
      { name: "Rose Kaju", price: 100 },
      { name: "Anjeer", price: 120 },
      { name: "Mango Kaju", price: 130 },
      { name: "Hazelnut", price: 130 },
      { name: "Kaju Anjeer", price: 140 },
      { name: "Roasted Almonds", price: 150 },
      { name: "Royal Dry Fruits", price: 160 },
    ],
  },
  {
    category: "Milk Shakes (250ml/350ml)",
    icon: "🥛",
    items: [
      { name: "Chocolate", price: 140 },
      { name: "Nutella", price: 140 },
      { name: "Oreo", price: 140 },
      { name: "Kitkat", price: 140 },
      { name: "Brownie", price: 140 },
      { name: "Almond Carnival", price: 140 },
      { name: "Kinder Bueno", price: 140 },
      { name: "Mango", price: 100 },
      { name: "Strawberry", price: 100 },
      { name: "Dark Chocolate", price: 100 },
      { name: "Biscoff", price: 100 },
    ],
  },
  {
    category: "Signature Shots",
    icon: "🏆",
    items: [
      { name: "Dubai Kunafa Maxx", price: 210 },
      { name: "Rocher Brownie Fudge", price: 210 },
      { name: "Nutella Brownie Fudge", price: 190 },
    ],
  },
  {
    category: "Bournville Shakes",
    icon: "🍫",
    items: [
      { name: "Bournville", price: 140 },
      { name: "Strawberry Bournville", price: 150 },
      { name: "Bournville Brownie", price: 150 },
      { name: "Bournville Extreme", price: 200 },
    ],
  },
  {
    category: "Waffles Wander",
    icon: "🧇",
    items: [
      { name: "Belgium Milk Chocolate", price: 130 },
      { name: "Belgium White Chocolate", price: 130 },
      { name: "Belgium Dark Chocolate", price: 130 },
      { name: "Cadbury Waffle", price: 130 },
      { name: "Brownie Waffle", price: 130 },
      { name: "Oreo Waffle", price: 130 },
      { name: "Kitkat Waffle", price: 130 },
      { name: "Triple Chocolate Waffle", price: 130 },
      { name: "Coffee Crunch", price: 130 },
      { name: "Butterscotch Waffle", price: 130 },
      { name: "Brownie Kitkat Waffle", price: 150 },
      { name: "Hazelnut Waffle", price: 150 },
      { name: "Red Velvet Waffle", price: 150 },
      { name: "Nutella Naked", price: 150 },
      { name: "Crunchy Nutella", price: 150 },
      { name: "Biscoff Waffle", price: 150 },
      { name: "Biscoff Nutella", price: 150 },
      { name: "KiKi And Cookie", price: 150 },
      { name: "Londan Waffle", price: 150 },
      { name: "Dry-fruit Based Nutella Waffle", price: 170 },
      { name: "Beuno Waffle", price: 170 },
      { name: "Kunafa Waffle", price: 180 },
      { name: "Roacher Waffle", price: 200 },
    ],
  },
  {
    category: "Melt Down Brownies",
    icon: "🍫",
    items: [
      { name: "Choco Lava Cake", price: 80 },
      { name: "Redvelvet Lava Cake", price: 90 },
      { name: "Brownie Fudge", price: 110 },
      { name: "Brownie Chocochips", price: 120 },
      { name: "Red Velvet Fudge", price: 140 },
      { name: "Belgium Brownie", price: 140 },
      { name: "White Chocolate Brownie", price: 140 },
      { name: "Nutella Brownie Fudge", price: 140 },
      { name: "Oreo Brownie Fudge", price: 150 },
      { name: "Hazelnut Brownie Fudge", price: 150 },
      { name: "Sizzling Brownie", price: 150 },
      { name: "Nutella Kitkat Fudge", price: 150 },
      { name: "Cadbary Brownie", price: 150 },
      { name: "Roasted Almond Brownie", price: 160 },
      { name: "Macadamia Almonds Brownie", price: 180 },
      { name: "Rocher Brownie", price: 180 },
      { name: "Kunafa Brownie", price: 180 },
      { name: "Biscoff Brownie", price: 180 },
    ],
  },
  {
    category: "Misu Bar",
    icon: "🍮",
    items: [
      { name: "Vietnam Style Tiramisu", price: 180 },
      { name: "Red Velvet Misu", price: 200 },
      { name: "Biscoff Misu", price: 220 },
      { name: "Chocomisu", price: 220 },
      { name: "Nutella Misu", price: 240 },
    ],
  },
  {
    category: "Ice Cream",
    icon: "🍦",
    items: [
      { name: "Vanilla", price: 50 },
      { name: "Strawberry", price: 50 },
      { name: "Butterscotch", price: 60 },
      { name: "Cookies And Cream", price: 70 },
      { name: "Choco Chips", price: 70 },
      { name: "Black Currant", price: 70 },
      { name: "American Nuts", price: 70 },
      { name: "Roasted Almonds", price: 80 },
      { name: "Rajbhog", price: 80 },
      { name: "Raj Wadi", price: 80 },
      { name: "Mud Cake", price: 80 },
      { name: "Kesar Pista", price: 80 },
      { name: "Dark Chocolate", price: 90 },
      { name: "Mocha Brownie Fudge", price: 90 },
    ],
  },
  {
    category: "Hot Zone",
    icon: "☕",
    items: [
      { name: "Hot Coffee", price: 80 },
      { name: "White Mocha", price: 100 },
      { name: "Nutella Mocha", price: 100 },
      { name: "Vanilla Mocha", price: 100 },
    ],
  },
  {
    category: "Hot Chocolate",
    icon: "☕",
    items: [
      { name: "Hot Chocolate", price: 130 },
      { name: "Roasted Hazelnut", price: 130 },
      { name: "Brownie Hot Chocolate", price: 140 },
      { name: "Coffee Hot Chocolate", price: 140 },
      { name: "Nutella Hot Chocolate", price: 140 },
      { name: "Dark Hot Chocolate", price: 140 },
    ],
  },
  {
    category: "Cold Coffee",
    icon: "🧊",
    items: [
      { name: "Creamy Cold Coffee", price: 110 },
      { name: "Chocolate Cold Coffee", price: 140 },
      { name: "Hazelnut Cold Coffee", price: 140 },
      { name: "Brownie Cold Coffee", price: 140 },
      { name: "Nutella Cold Coffee", price: 140 },
      { name: "Caramel Cold Coffee", price: 140 },
      { name: "Biscoff Cold Coffee", price: 140 },
    ],
  },
  {
    category: "Mini But Dangerous (Pancakes)",
    icon: "🥞",
    items: [
      { name: "Milk Chocolate", price: 130 },
      { name: "Dark Knight", price: 130 },
      { name: "White Beauty", price: 140 },
      { name: "Triple Loaded", price: 140 },
      { name: "Kitkat Break", price: 140 },
      { name: "Biscoff Crunch", price: 140 },
      { name: "Nutella Loaded", price: 140 },
      { name: "Oreo", price: 140 },
      { name: "Crunchy Nutella", price: 140 },
      { name: "Red Velvet", price: 140 },
    ],
  },
  {
    category: "Fries",
    icon: "🍟",
    items: [
      { name: "Simply Salted Fries", price: 79 },
      { name: "Peri Peri Fries", price: 99 },
      { name: "Peri Peri Cheese Blast", price: 119 },
      { name: "Cheese Loaded", price: 139 },
      { name: "Junglee Fries", price: 139 },
      { name: "Special Fries Bowl", price: 149 },
    ],
  },
  {
    category: "Sandwich",
    icon: "🥪",
    items: [
      { name: "Veg Sandwich", price: 79 },
      { name: "Cheese Grill Sandwich", price: 99 },
      { name: "Cheese Corn Sandwich", price: 99 },
      { name: "Schezwan Cheese Corn", price: 99 },
      { name: "Paneer Tandoori Cheese", price: 129 },
      { name: "Paneer Makhani", price: 129 },
    ],
  },
  {
    category: "Momo's",
    icon: "🥟",
    items: [
      { name: "Fried Momos", price: 79 },
      { name: "Peri Peri Momos", price: 89 },
      { name: "Veg Paneer Momos", price: 99 },
      { name: "Kurkure Veg Momos", price: 99 },
      { name: "Cheese Corn Momos", price: 99 },
      { name: "Kurkure Paneer Momos", price: 119 },
      { name: "Special Kadhai Momos (Tandoori/Peri Peri/Chipotle)", price: 139 },
    ],
  },
  {
    category: "Maharaja Sandwich",
    icon: "🥪",
    items: [
      { name: "Paneer Tikka Sandwich", price: 149 },
      { name: "Bombay Masala Sandwich", price: 159 },
      { name: "Special Jumbo Grill", price: 159 },
    ],
  },
  {
    category: "Maggi",
    icon: "🍜",
    items: [
      { name: "Plain Masala Maggi", price: 69 },
      { name: "Masala Cheese Maggi", price: 79 },
      { name: "Peri Peri Masala Maggi", price: 79 },
      { name: "Tandori Maggi", price: 79 },
      { name: "Cheese Peri Peri Maggi", price: 89 },
      { name: "Tandori Cheese Maggi", price: 89 },
      { name: "Cheese Spicy Maggi", price: 119 },
      { name: "Punjabi Maggi", price: 109 },
      { name: "Punjabi Cheese Maggi", price: 129 },
    ],
  },
  {
    category: "Burger",
    icon: "🍔",
    items: [
      { name: "Veg Burger", price: 69 },
      { name: "Aloo Tikki Burger", price: 79 },
      { name: "Veg Cheese Burger", price: 79 },
      { name: "Peri Peri Burger", price: 89 },
      { name: "Schezwan Burger", price: 109 },
      { name: "Paneer Tikka Burger", price: 119 },
      { name: "Four Cheese Burger", price: 139 },
    ],
  },
];

// Extra topping (flat add-on, applies across savoury items per menu note)
const EXTRA_TOPPING_PRICE = 20;
